#!/bin/bash
# vim: ft=zsh:ts=4:sw=4
# shellcheck disable=2010,1090,2034

# init hooks auto-function
autoload -U add-zsh-hook

# load env files
__load_env() {
    local ENV_FILE file_found
    # TODO: Maybe this should load multiple files ¯\\_(ツ)_/¯
    ENV_FILE=".nic"
    ls -a |
        grep "^$ENV_FILE" 2>/dev/null |
        sed "s:^:$PWD/:" |
        while read -rs file_found; do
            if [ -n "$file_found" ]; then
                echo "Using environment file '$file_found'"
                # TODO: check if the variables has the `export` prefix and if
                # not add it on the fly
                . "$file_found"
            fi
        done
}
chpwd_functions+=(__load_env)
__load_env

# use .nvmrc to load node project version
__load_nvmrc() {
    local node_version nvmrc_path nvmrc_node_version
    node_version="$(nvm version)"
    nvmrc_path="$(nvm_find_nvmrc)"
    if [ -n "$nvmrc_path" ]; then
        nvmrc_node_version=$(nvm version "$(cat "${nvmrc_path}")")
        if [ "$nvmrc_node_version" = "N/A" ]; then
            nvm install
        elif [ "$nvmrc_node_version" != "$node_version" ]; then
            nvm use
        fi
    elif [ "$node_version" != "$(nvm version default)" ]; then
        echo "Reverting to nvm default version"
        nvm use default
    fi
}
chpwd_functions+=(__load_nvmrc)
__load_nvmrc

# change emoji in the PS1
__change_emoji() {
    local EMOJIS EMOJI_INDEX ASCII SELECTED_EMOJI
    ASCII=(
        "(づ￣ ³￣)づ"
        "(ง •̀_•́)ง"
        "(●__●)"
        "(╯°□°）╯︵ ┻━┻"
        "(▀̿Ĺ̯▀̿ ̿)"
        "ᕦ(ò_óˇ)ᕤ"
    )
    if ! [[ $(uname -s) =~ ^[Dd]arwin$ ]] && [ -z "$DISPLAY" ]; then
        EMOJIS=(${ASCII[*]})
    else
        EMOJIS=(
            "🫨"
            "🫠"
            "🥸"
            "🤨"
            ${ASCII[*]}

        )
    fi
    RANDOM_NUM=$RANDOM
    EMOJI_INDEX=$((RANDOM_NUM % ${#EMOJIS[@]} + 1))
    SELECTED_EMOJI=${EMOJIS[$EMOJI_INDEX]}
    if [[ $(</tmp/prompt-emoji) = ${SELECTED_EMOJI} ]]; then
        PLUS=$((RANDOM_NUM + 1))
        EMOJI_INDEX=$((PLUS % ${#EMOJIS[@]} + 1))
        SELECTED_EMOJI=${EMOJIS[$EMOJI_INDEX]}
    fi
    SPACESHIP_CHAR_SUFFIX="${SELECTED_EMOJI} "
    touch /tmp/prompt-emoji
    echo ${SELECTED_EMOJI} > /tmp/prompt-emoji
}
chpwd_functions+=(__change_emoji)
__change_emoji
