#!/bin/bash
# vim: ft=zsh:ts=4:sw=4
# shellcheck disable=1090

addToPath() {
    local ITEM
    for ITEM in "$@"; do
        PATH="$ITEM:$PATH"
    done
}

# homebrew
addToPath /opt/homebrew/bin

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && source "$NVM_DIR/nvm.sh"

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# bin
addToPath ~/.bin
addToPath ~/.local/bin
addToPath ~/.scripts

# yarn
addToPath ~/.yarn/bin
addToPath ~/.config/yarn/global/node_modules/.bin

# golang
addToPath ~/{.,}go/bin

# rust
addToPath ~/.cargo/bin

# dotnet
addToPath ~/.dotnet

# pyenv (python)
addToPath "$(pyenv root)/shims"

# php@7.4
addToPath /usr/local/opt/php@8.1/bin
addToPath /usr/local/opt/php@8.1/sbin

# vscode
addToPath /Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/

# bun
addToPath ~/.bun/bin

# ruby
addToPath ~/.rvm/bin

# LM Studio CLI (lms)
addToPath ~/.lmstudio/bin
