#!/bin/bash
# vim: ft=zsh:ts=4:sw=4

######################################################################
#                                                                    #
# all inside this file will be initialized at the login of the shell #
#                                                                    #
######################################################################

gcl(){
    # Clones a repository and cd into it ( :
    local repo
    local repo_basename
    local repo_name

    repo="$1"
    repo_basename=$(basename "$repo")
    repo_name=${repo_basename%.*} # this remove the `.git` at the end

    # Validate that you only pass one parameter
    if [ $# -gt 1 ]
    then
      echo "Just pass the repo URL as a parameter"
      exit 1
    fi

    # if cloning the repo fails finish this function
    if ! git clone "$repo"; then
        return 1
    fi

    if [ -n "$TMUX" ]; then
        cdtmux "$repo_name"
		tmux rename-window "$repo_name"
        exit 0
    else
        cd "$repo_name" || exit
    fi
}

