#!/bin/bash
# vim: ft=zsh:ts=4:sw=4
# shellcheck disable=2142

# Uses fzf to search for files and open then with your default editor
# ===================================================================
__edit_files() {
    local selected_files
    selected_files=$(eval $FZF_DEFAULT_COMMAND | fzf -m)  # Find all files in the current directory
    if [[ -n "$selected_files" ]]; then
        $EDITOR $(echo $selected_files)
    fi
}
bindkey -M viins '^e' __edit_files
zle -N __edit_files

# map 'C-z' to 'fg' command, this would allow you to toggle
# between your current program and the terminal
# =========================
__foreground_job(){
    fg 2> /dev/null
    zle reset-prompt
}
zle -N __foreground_job
bindkey -M viins '^Z' __foreground_job

# edit commandline
bindkey -M viins '^X^E' edit-command-line
