[manager]
prepend_keymap = [
	# goto
	{ on = [ "g", "d" ], run = "cd ~/projects/dotfiles", desc = "Go to the dotfiles directory" },
	{ on = [ "g", "D" ], run = "cd ~/Downloads", desc = "Go to the downloads directory" },
	{ on = [ "g", "w" ], run = "cd ~/work", desc = "Go to the work directory" },

	## diff ( https://github.com/yazi-rs/plugins/tree/main/diff.yazi )
	{ on = "<C-d>", run = "plugin diff", desc = "Diff the selected with the hovered file" },

	## relative-motions ( https://github.com/dedukun/relative-motions.yazi )
	{ on = [ "1" ], run = "plugin relative-motions 1", desc = "Move in relative steps" },
	{ on = [ "2" ], run = "plugin relative-motions 2", desc = "Move in relative steps" },
	{ on = [ "3" ], run = "plugin relative-motions 3", desc = "Move in relative steps" },
	{ on = [ "4" ], run = "plugin relative-motions 4", desc = "Move in relative steps" },
	{ on = [ "5" ], run = "plugin relative-motions 5", desc = "Move in relative steps" },
	{ on = [ "6" ], run = "plugin relative-motions 6", desc = "Move in relative steps" },
	{ on = [ "7" ], run = "plugin relative-motions 7", desc = "Move in relative steps" },
	{ on = [ "8" ], run = "plugin relative-motions 8", desc = "Move in relative steps" },
	{ on = [ "9" ], run = "plugin relative-motions 9", desc = "Move in relative steps" },

	## toggle-pane
	{ on = ["'", "t", "h"], run = "plugin toggle-pane min-parent", desc = "Toggle left pane" },
	{ on = ["'", "t", "l"], run = "plugin toggle-pane min-preview", desc = "Toggle right pane" },
]
