#!/bin/bash -e

# This `add`, `commit --amend` and `git push -f --no-verify`
# all the changes in the current branch to its remote one

CURRENT_BBRANCH=$(gcb)

if protected_branch "$CURRENT_BBRANCH" "$@"; then
	exit 1
fi

git add -A
eval "git commit $sighned --amend --no-edit --no-verify"
git push origin "$CURRENT_BBRANCH" -f
