#!/bin/bash
# shellcheck disable=1090

__source_glob() {
    local TARGET TARGET_BASENAME IS_IGNORED

    for TARGET in "${@:?No files to be sourced...}"; do
        TARGET_BASENAME=$(basename "$TARGET")
        IS_IGNORED=$(grep -E "\b$TARGET_BASENAME\b" <<<"${IGNORED_FILES[*]}" 2>/dev/null)

        [[ "$IS_IGNORED" ]] && continue

        [ -f "$TARGET" ] && source "$TARGET"
    done
}

sourceIfExists() { # Source file if exists (glob pattern)
    local IGNORED_FILES

    IGNORED_FILES=(
        .bash_profile
        .bash_history
        .bash_logout
        Session.vim
    )

    while getopts ":i:" OPT; do
        case $OPT in
        i)
            IGNORED_FILES+=("$OPTARG")
            ;;
        \?)
            echo "Invalid option (-$OPTARG)"
            ;;
        esac
    done
    shift $((OPTIND - 1))

    __source_glob "$@"
}
